"""
BIKIN FILE BARU TERSERAH NAMANYA APA
TERUS BIKIN VARIABEL UMUR DENGAN NILAI ANGKA TERSERAH KASIH KOMEN TIPE DATANYA APA
TERUS BIKIN KODE
JIKA UMUR LEBIH ATAU SAMA DENGAN 17 TUNJUKKAN TEKS "KAMU DEWASA!" DI TERMINAL
JIKA TIDAK TUNJUKKIN TEKS "KAMU ANAK ANAK" DI TERMINAL    
"""